rule all:
    input:
        "results/checks/datamgt.txt",
        "results/checks/prediction_done.txt",
        "results/checks/tables_done.txt",

include: "rules/common.smk",
include: "rules/data_mgt.smk",
include: "rules/prediction.smk",
include: "rules/tables.smk",