data_path: "/mnt/work/workbench/hedvigs/hedvproj/hed_ML/results/geno/plink"

# Pathways
root_path      : "/mnt/work/workbench/hedvigs/snake_book/econ/"

ROOT: "."
sub2root: "../../"
rules          : "rules/"
conda          : "conda/"
resources      : "resources/"
log            : "logs/"
results        : "results/"

src_data         : "resources/data/"
out_tables       : "results/tables/"
checks           : "results/checks/"
scripts_analysis : "workflow/scripts/analysis/"
scripts_tables   : "workflow/scripts/tables/"
scripts_data_mgt : "workflow/scripts/data_management/"
out_data         : "results/data/"
out_data_gen     : "results/data/gen/"
src_data_pheno   : "resources/data/pheno_files/"


src_data_gen   : "src/data/gen/"
src_data_gen_m : "src/data/gen/maternal/"
src_data_gen_f : "src/data/gen/fetal/"
src_data_mgt   : "src/data_management/"
src_analysis   : "src/analysis/"
src_lib        : "src/lib/"
src_model_specs: "src/model_specs/"
src_data_specs : "src/data_specs/"
src_table_specs: "src/table_specs/"
src_tables     : "src/tables/"
src_figures    : "src/figures/"
src_paper      : "src/paper/"
src_slides     : "src/slides/"

out_analysis   : "out/analysis/"
out_figures    : "out/figures/"
out_paper      : "out/paper/"
out_slides     : "out/slides/"
out_params     : "out/params/"
