data_path: "/mnt/work/workbench/hedvigs/hedvproj/hed_ML/results/geno/plink"


# Pathways
root_path      : "/mnt/work/hedvig/grepos/plab_workflow/"

ROOT: "."
sub2root: "../../"
rules          : "rules/"
conda          : "conda/"
resources      : "resources/"
log            : "logs/"
results        : "results/"
checks         : "results/checks/"
scripts        : "workflow/scripts/"
snp_list       : "config/snplist.list"

src_data         : "resources/data/"
src_data_pheno   : "resources/data/pheno_files/"

scripts_analysis : "workflow/scripts/analysis/"
scripts_tables   : "workflow/scripts/tables/"
scripts_data_mgt : "workflow/scripts/data_management/"
scripts_postprocess : "/scripts/postprocess/"

out_data         : "results/data/"
out_data_gen     : "results/data/gen/"
out_pred         : "results/prediction/"
out_scores       : "results/scores/"
out_params       : "results/params/"
out_summary      : "results/summary/"
out_tables       : "results/report/tables/"
out_figures      : "results/report/figures/"
out_report       : "results/report/"


src_data_gen   : "src/data/gen/"
src_data_gen_m : "src/data/gen/maternal/"
src_data_gen_f : "src/data/gen/fetal/"
src_data_mgt   : "src/data_management/"
src_analysis   : "src/analysis/"
src_lib        : "src/lib/"
src_model_specs: "src/model_specs/"
src_data_specs : "src/data_specs/"
src_table_specs: "src/table_specs/"
src_tables     : "src/tables/"
src_figures    : "src/figures/"
src_paper      : "src/paper/"
src_slides     : "src/slides/"

out_analysis   : "out/analysis/"
out_paper      : "out/paper/"
out_slides     : "out/slides/"

